--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/HmmHmmmm/Market
build-by-default: true
branches:
- master
projects:
  Market:
    path: ""
    icon: "images/icon.jpg"
    libs:
    - src: thebigsmilexd/customui/customui
      version: ^3.0.0
    - src: muqsit/InvMenu/InvMenu
      version: ^3.1.0
...
