name: Market
version: 1.1
api: 3.11.0
author: HmmHmmmmm
main: hmmhmmmm\market\Market
website: https://github.com/HmmHmmmm/Market
depend:
- EconomyAPI

permissions:
  market:
    default: false
    children:
      market.command:
        default: false
        children:
          market.command.info:
            default: op
          market.command.addshop:
            default: true
          market.command.removeshop:
            default: true
          market.command.settext:
            default: true
          market.command.setprice:
            default: true